{{/*
Copyright (c) HashiCorp, Inc.
SPDX-License-Identifier: MPL-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: terraform-enterprise
  namespace: {{ .Release.Namespace }}
  annotations:
    checkov.io/skip1: CKV_K8S_21= The default namespace should not be used
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: https-port
      port: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: {{ .Values.tfe.privateHttpsPort }}
      appProtocol: {{ .Values.service.appProtocol }}
  selector:
    app: terraform-enterprise
